#pragma config(Sensor, S1,     infrared,       sensorHiTechnicIRSeeker1200)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
int channelIR;
task main()
{
while(true){
channelIR = SensorValue(infrared);
}

}
