#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

//defines the buttons on the controller

task main()
{
getJoystickSettings(joystick);
//make sure joystick values are updated
while(true)
{
int x = joystick.joy1_x2; //sideways
int y = joystick.joy1_y2; //forward and backward
int z = joystick.joy1_y1; //rotation
//set x y and z to the joystick values
//x is horizontal, y is vertical, 1 and 2 are different buttons

//int left, right;
//motor[frontleft]=-(y+x+z);
//motor[backleft]=-(y-x+z);
//motor[frontright]=(y-x-z);
//motor[backright]=(y+x-z);


//	left = joystick.joy1_y1;
//	right = joystick.joy1_y2;

	motor[frontRight] = (y-x);
	motor[backRight] = (y+x);
	motor[frontLeft] = (y+x);
	motor[backLeft] = (y-x);

}
}
