#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     Gyro,           sensorI2CMuxController)
#pragma config(Sensor, S3,     Sonar,          sensorSONAR)
#pragma config(Sensor, S4,     Accel,          sensorI2CHiTechnicAccel)
#pragma config(Motor,  mtr_S1_C1_1,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     transportA,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     transportB,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    scoreA,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_2,    scoreB,               tServoStandard)
#pragma config(Servo,  srvo_S2_C1_3,    rollingback,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    rollingside,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

float initial; 	//initial gyro reading
float heading; 	//robots current yaw
float radheading;   //heading in radians
int lastTime = 0;	//last time header was updated, used to find average change in rotation
float FLset; //front-left set, refers to Front-Left and Back-Right
float FRset; //front-right set, refers to Front-Right and Back-Left motor
float joyAngle; // angle of the first joystick
float currHeading;
float sonarValue;
float delTime = 0;//calibration
float prevHeading = 0;
float curRate = 0;

void motorTrigger(tMotor motorCall,int x,int y,int z);


void initializeRobot()
{
	for(int i = 0; i < 100; i++){
		initial += SensorValue[S4];
		wait10Msec(1);
	}
	initial = initial / 100;
	return;
}

task FPSDrive()
{
	int deadZone = 15;
	while(true)
	{
		int accelValue = SensorValue(Accel); //set accelerometer value to accelValue
		int gyroValue = SensorValue(Gyro); //set gyroscope value to gyroValue

		nxtDisplayCenteredBigTextLine(5,"%d",gyroValue); //display gyroValue to NXT
		nxtDisplayCenteredBigTextLine(5,"%d",accelValue); //display accelValue to NXT

		getJoystickSettings(joystick);

		int y= joystick.joy1_y1;
		int x= joystick.joy1_x1;
		int z= joystick.joy1_x2;

		int trueX = (cosDegrees(currHeading)*x)-(sinDegrees(currHeading)*y); //sets trueX to rotated x value
		int trueY = (sinDegrees(currHeading)*x)+(cosDegrees(currHeading)*y); //sets trueY to rotated y value

		x = trueX;
		y = trueY;

		if ( (abs(joystick.joy1_x1) < deadZone) && (abs(joystick.joy1_y1) < deadZone) && (abs(joystick.joy1_x2) < deadZone)) //drive only if joystick out of dead zones
		{
			x = 0;
			y = 0;
			z = 0;
		}

		motorTrigger(frontright,x,-y,-z);
		motorTrigger(backright,-x,-y,-z);
		motorTrigger(frontleft,x,y,-z);
		motorTrigger(backleft,-x,y,-z);
	}
}

task getHeading() {


	HTGYROstartCal(Gyro);
	PlaySound(soundBeepBeep);
	while (true) {
		time1[T1] = 0;
		curRate = HTGYROreadRot(Gyro);
		if (abs(curRate) > 3) //sets deadzones for gyroscope
		{
			prevHeading = currHeading;
			currHeading = prevHeading + curRate * delTime; //changes current heading based on the rate of change and time elapsed
			if (currHeading > 360) currHeading -= 360; //keeps current heading between 0 and 360
			else if (currHeading < 0) currHeading += 360; // keeps curent heading between 0 and 360
		}
		wait1Msec(5);
		delTime = ((float)time1[T1]) / 1000;
	}
}

void motorTrigger(tMotor motorCall,int x,int y,int z)
{
	motor[motorCall]= (y+x+z);
}


task   getXY()
{  //365.76

}//18in = 45.72

task display()
{
	while (true){
		eraseDisplay();
		nxtDisplayCenteredTextLine(0, "Heading: %d", currHeading);
		nxtDisplayCenteredTextLine(1, "joyAngle: %d", joyAngle);
		nxtDisplayCenteredTextLine(2, "Sonar: %d", sonarValue);
		wait1Msec(20);
	}
}

task getSonar()
{
	while(true){
		sonarValue = SensorValue(Sonar);}
}

task getAccel()
{
	int X_Accel;
	int Y_Accel;

	//X_Accel = SensorValue[xAxis]/2000;
	//Y_Accel = SensorValue[yAxis];

}

task calibrateDrive()//needs work, doing some wack stuff
{
	while(true)
	{
		if(joy1Btn(1)&&joy1Btn(3))
		{
			PlaySound(soundUpwardTones);
			wait1Msec(500);
			/*

			initializeRobot();
			HTGYROstartCal(Gyro);
			delTime = 0;//calibration
			prevHeading = 0;
			curRate = 0;
			wait1Msec(500);
			*/
		}
	}
}

task sweeper()
{
	while(joy2Btn(5))
	{
		motor[collector] = 75;
	}
	while(joy2Btn(7))
	{
		motor[collector] = -75;
	}
}

task functions()
{
	while(true){
		int y2 = joystick.joy2_y2 /128*85;
		if(abs(joystick.joy2_y2) > 15)
		{
			motor[transportA] = y2;
			motor[transportB] = y2;
		}

		if (joy2Btn(1))//ready position
		{
			servo[scoreA] = 75;
			servo[scoreB] = 255-75;
		}
		if (joy2Btn(2))//score position
		{
			servo[scoreA] = 240;
			servo[scoreB] = 10;
		}
		if (joy2Btn(3))//resting position
		{
			servo[scoreA] = 10;
			servo[scoreB] = 240;
		}
		if (joy1Btn(5))
		{
			servo[rollingback] = 50; //clamp onto rolling goal in back of robot
		}
		if (joy1Btn(7))
		{
			servo[rollingback] = 0; //release rolling goal
		}
		if (joy1Btn(6))
		{
			servo[rollingside] = 50; //clamp onto rolling goal on side of robot
		}
		if (joy1Btn(8))
		{
			servo[rollingside] = 0; //release rolling goal
		}
	}
}

	task main()
	{
		initializeRobot();
		StartTask(display);
		StartTask(getHeading);
		StartTask(FPSDrive);
		StartTask(getSonar);
		StartTask(calibrateDrive);
		StartTask(functions);
		StartTask(sweeper);
		while (true){
			wait1Msec(10000);
		}

	}
