#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S3, HTServo,  HTServo,  none,     none)
#pragma config(Sensor, S4, HTTMUX,         sensorHiTechnicTouchMux)
#pragma config(Motor,  mtr_S1_C1_1,     ring,          tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C1_2,     finger,        tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_1,     up1,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C2_2,     up2,           tmotorTetrix, PIDControl)
#pragma config(Motor,  mtr_S1_C3_1,     backright,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     frontright,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backleft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     frontleft,     tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S3_C1_1,    IRlift,               tServoStandard)
#pragma config(Servo,  srvo_S3_C1_2,    claw,                 tServoStandard)
#pragma config(Servo,  srvo_S3_C1_3,    elbow,                tServoStandard)
#pragma config(Servo,  srvo_S3_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S3_C1_6,    servo6,               tServoNone)
#pragma config(Servo,  srvo_S3_C2_1,    shoulder,               tServoStandard)
#pragma config(Servo,  srvo_S3_C2_2,    ,             tServoNone)
#pragma config(Servo,  srvo_S3_C2_3,    rings,                tServoStandard)
#pragma config(Servo,  srvo_S3_C2_4,    IRpivot,              tServoStandard)
#pragma config(Servo,  srvo_S3_C2_5,    release,              tServoStandard)
#pragma config(Servo,  srvo_S3_C2_6,    flip,                 tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

#include "hitechnic-touchmux.h"
#include "lego-touch.h"

void initializeRobot()
{

servo[flip]=255;
servo[IRlift]=0;

	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}

//accuracy threshold for driving on joysticks
int thresabs(int n){
	if(abs(n) < 10){
		n=0;
	}
	return (100*n/128);
}

//servo toggle function
void servotoggle(short buttonname, bool Pressedornot, TServoIndex servoName, int lower, int upper)
{
	if(buttonname)
	{
		int mid = (lower + upper) / 2;

		if(!Pressedornot)
		{
			Pressedornot = true;

			if(ServoValue[servoName]>mid)
			{
				servo[servoName]=lower;
			}
			else
			{
				servo[servoName]=upper;
			}
		}
	}
	else
	{
		Pressedornot = false;
	}
}

task main()
{
	// This is the code to define the variables for direct mecanum code.
	SensorType[S4] = sensorHiTechnicTouchMux;

	bool button15 = false;
	bool button26 = false;

	int level = 0;

	//bool alreadyPressed = false;

	initializeRobot();

	waitForStart();

	while(true)

	{
		getJoystickSettings(joystick);

		// The sensor value is a 4-bit map indicating which of the possible four
		// touch sensors are pressed.
		int ButtonMap = SensorValue[S4];

		int x = thresabs(joystick.joy1_x1);
		int y = thresabs(joystick.joy1_y1);

		if(joystick.joy1_TopHat==0)
		{
			motor[frontleft]=100;
			motor[backleft]=100;
			motor[frontright]=-100;
			motor[backright]=-100;
		}

		else if(joystick.joy1_TopHat==2)
		{
			motor[frontleft]=100;
			motor[backleft]=-100;
			motor[frontright]=100;
			motor[backright]=-100;
		}

		else if(joystick.joy1_TopHat==4)
		{
			motor[frontleft]=-100;
			motor[backleft]=-100;
			motor[frontright]=100;
			motor[backright]=100;
		}

		else if(joystick.joy1_TopHat==6)
		{
			motor[frontleft]=-100;
			motor[backleft]=100;
			motor[frontright]=-100;
			motor[backright]=100;
		}
		else if(abs(joystick.joy1_y1)>0 && abs(joystick.joy1_x1)>0)
		{
			motor[frontleft]=y+x;
			motor[backleft]=y-x;
			motor[frontright]=-(y-x);
			motor[backright]=-(y+x);
		}
		else if(joy1Btn(5))
		{
			motor[frontleft]=-100;
			motor[backleft]=-100;
			motor[frontright]=-100;
			motor[backright]=-100;
		}
		else if(joy1Btn(6))
		{
			motor[frontleft]=100;
			motor[backleft]=100;
			motor[frontright]=100;
			motor[backright]=100;
		}
		else
		{
			motor[frontleft]=0;
			motor[backleft]=0;
			motor[frontright]=0;
			motor[backright]=0;
		}

		//dispenser in and out
		if(joystick.joy1_y2>10 && !(ButtonMap & 0x01))
		{
			motor[ring]=-joystick.joy1_y2*100/128;
		}
		else if(joystick.joy1_y2<10 && !(ButtonMap & 0x02))
		{
			motor[ring]=-joystick.joy1_y2*100/128;
		}
		else
		{
			motor[ring]=0;
		}

		if(joy1Btn(7))
		{
			servo[rings]=36;
		}
		else if(joy1Btn(8))
		{
			servo[rings]=90;
		}

		//servotoggle(joy1Btn(8), button15, rings, 36, 90);

		//elevator threshold up and down
		if(abs(joystick.joy2_y2)>10)
		{
			motor[up1]=joystick.joy2_y2;
			motor[up2]=joystick.joy2_y2;
		}
		else
		{
			motor[up1]=0;
			motor[up2]=0;
		}

		motor[finger]=joystick.joy2_x1;

		servotoggle(joy2Btn(6), button26, flip, 0, 255);

		if(joy2Btn(1))
		{
			servo[release]=20;
		}
		else if(joy2Btn(2))
		{
			servo[release]=70;
		}
		else if(joy2Btn(3))
		{
			servo[release]=170;
		}



/*
		if(joy1Btn(4))
		{

			nMotorEncoderTarget[motorA] = 10;

			motor[up1]=-50;
			motor[up2]=-50;
			while(nMotorRunState[motorA] != runStateIdle)
			{}

			motor[up1]=0;
			motor[up2]=0;

			level = 0;
		}

		else if(joy1Btn(3))
		{

			nMotorEncoderTarget[motorA] = 1080;

			motor[up1]=100;
			motor[up2]=100;
			while(nMotorRunState[motorA] != runStateIdle)
			{}

			motor[up1]=0;
			motor[up2]=0;

			level = 3;
		}

		else if(joy1Btn(2))
		{

			nMotorEncoderTarget[motorA] = 720;

			if(level<2)
			{
				motor[up1]=100;
				motor[up2]=100;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

			}

			else if(level>2)
			{
				motor[up1]=-50;
				motor[up2]=-50;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;


			}
			level = 2;
		}

		else if(joy1Btn(1))
		{

			nMotorEncoderTarget[motorA] = 360;

			if(level>1)
			{
				motor[up1]=-50;
				motor[up2]=-50;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

			}

			else if(level<1)
			{
				motor[up1]=100;
				motor[up2]=100;

				while(nMotorRunState[motorA] != runStateIdle)
				{}

				motor[up1]=0;
				motor[up2]=0;

			}
			level = 1;
		}

		else
		{
			motor[up1]=0;
			motor[up2]=0;
		}
*/
	}
}
