#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Sensor, S2,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Motor,  mtr_S1_C1_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backLeft,      tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

float initial; 	//initial gyro reading
int lastTime = 0;	//last time header was updated, used to find average change in rotation
float currHeading;//USED

float delTime = 0;//calibration
float prevHeading = 0; //USED
float curRate = 0;
int deadZone = 15;
float calibrate =0;
float slideBtn = 0;
float clampPress = 0;
float globalZ;

//defines the buttons on the controller

void initializeRobot()
{
	initial = 0;
	for(int i = 0; i < 100; i++){//Sensor
		initial += SensorValue[S4];
		wait10Msec(1);
	}
	initial = initial / 100;//Sensor
	return;
}

task FPSDrive
{
	while(true)
	{
	getJoystickSettings(joystick);

	int x = joystick.joy1_x1; //sideways
	int y = joystick.joy1_y1; //forward and backward
	int z = joystick.joy1_x2; //rotation
	//set x y and z to the joystick values
	//x is horizontal, y is vertical, 1 and 2 are different buttons

	int trueX = (cosDegrees(currHeading)*x)-(sinDegrees(currHeading)*y); //sets trueX to rotated x value
	int trueY = (sinDegrees(currHeading)*x)+(cosDegrees(currHeading)*y);

	if ( (abs(joystick.joy1_x1) < 15) && (abs(joystick.joy1_y1) < 15)) //drive only if joystick out of dead zones
	{
		x = 0;
		y = 0;
	}
	x = trueX;
	y = trueY;

	//int left, right;
	motor[frontLeft]=(-y-x+z)*.75;
	motor[backLeft]= (-y+x+z)*.75; // -y-x||x+y
	motor[frontRight]=(y+x+z)*.75;//-y+x||-x+y
	motor[backRight]=(y-x+z)*.75;
	}
}

task getHeading() {
	HTGYROstartCal(Gyro);
	PlaySound(soundBeepBeep);
	while (true) {
		time1[T1] = 0;
		curRate = HTGYROreadRot(Gyro);
		if (abs(curRate) > 3) //sets deadzones for gyroscope
		{
			prevHeading = currHeading;
			currHeading = prevHeading + curRate * delTime; //changes current heading based on the rate of change and time elapsed
			if (currHeading > 360) currHeading -= 360; //keeps current heading between 0 and 360
			else if (currHeading < 0) currHeading += 360; // keeps curent heading between 0 and 360
		}
		wait1Msec(5);
		delTime = ((float)time1[T1]) / 1000;

	}
}

task main()
{
	initializeRobot();
	StartTask(getHeading);
	StartTask(FPSDrive);
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
	}
	while(true)
	{
		wait1Msec(1000);
	}
}
