#pragma config(Sensor, S1,     HTSMUX,      sensorI2CCustom)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "hitechnic-sensormux.h"
float sonarValue;
const tMUXSensor sonar1 = msensor_S1_1;
const tMUXSensor sonar2 = msensor_S1_2;
const tMUXSensor sonar3 = msensor_S1_3;
const tMUXSensor sonar4 = msensor_S1_4;
float sonarVal1;
float sonarVal2;
float sonarVal3;
float sonarVal4;
task main()
{
	while(true) {
sonarVal1 = SensorValue(sonar1);
sonarVal2 = SensorValue(sonar2);
sonarVal3 = SensorValue(sonar3);
sonarVal4 = SensorValue(sonar4);
nxtDisplayTextLine(0, "%d", sonarVal1);
nxtDisplayTextLine(2, "%d", sonarVal2);
nxtDisplayTextLine(4, "%d", sonarVal3);
nxtDisplayTextLine(5, "%d", sonarVal4);
}}
