#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Hubs,  S2, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     Gyro,           sensorI2CHiTechnicGyro)
#pragma config(Sensor, S4,     Accel,          sensorI2CHiTechnicAccel)
#pragma config(Motor,  mtr_S1_C1_1,     backRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeft,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_1,     emptyMotor,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     collector,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     frontRight,    tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     frontLeft,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     liftRight,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     liftLeft,      tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S2_C1_1,    emptyServo1,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_2,    emptyServo2,               tServoNone)
#pragma config(Servo,  srvo_S2_C1_3,    scoreRight,           tServoStandard)
#pragma config(Servo,  srvo_S2_C1_4,    scoreLeft,            tServoStandard)
#pragma config(Servo,  srvo_S2_C1_5,    rollingBack,          tServoStandard)
#pragma config(Servo,  srvo_S2_C1_6,    rollingSide,          tServoStandard)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "hitechnic-gyro.h"

float initial; 	//initial gyro reading
int lastTime = 0;	//last time header was updated, used to find average change in rotation
float currHeading;//USED
float delTime = 0;//calibration
float prevHeading = 0; //USED
float curRate = 0;
int deadZone = 15;
float calibrate =0;
float slideBtn = 0;
float clampPress = 0;
float globalZ;

void motorTrigger(tMotor motorCall,int x,int y,int z)
{
	motor[motorCall]= (y+x+z);
}

void initializeRobot()
{
	initial = 0;
	for(int i = 0; i < 100; i++){//Sensor
		initial += SensorValue[S4];
		wait10Msec(1);
	}
	initial = initial / 100;//Sensor

	servo[scoreLeft]=35;
	servo[scoreRight]=220;

	servo[rollingBack] = 200;
	servo[rollingSide] = 200; //rolling goal clamps are open

	return;
}


task FPSDrive()
{
	while(true)
	{
		int accelValue = SensorValue(Accel); //set accelerometer value to accelValue
		int gyroValue = SensorValue(Gyro); //set gyroscope value to gyroValue

		//nxtDisplayCenteredBigTextLine(5,"%d",gyroValue); //display gyroValue to NXT
		//nxtDisplayCenteredBigTextLine(5,"%d",accelValue); //display accelValue to NXT

		getJoystickSettings(joystick);

		int y= joystick.joy1_y1;
		int x= joystick.joy1_x1;
		int z= joystick.joy1_x2;

		int trueX = (cosDegrees(currHeading+calibrate)*x)-(sinDegrees(currHeading+calibrate)*y); //sets trueX to rotated x value
		int trueY = (sinDegrees(currHeading+calibrate)*x)+(cosDegrees(currHeading+calibrate)*y); //sets trueY to rotated y value
		int trueZ = atan(joystick.joy1_y1/joystick.joy1_x1);
		globalZ = trueZ;
		if(y < 0 && x > 0) //fourth quadrant (ask lucas)
		{
			trueZ = (abs(trueZ) + 270);
			globalZ = trueZ;
		}
		else if(y < 0 && x < 0)
		{
			trueZ = (trueZ + 180);
			globalZ = trueZ;
		}
		else if(y > 0 && x < 0)
		{
			trueZ =  (abs(trueZ) + 90);
			globalZ = trueZ;
		}
		nxtDisplayCenteredBigTextLine(5,"%d",globalZ);

		x = trueX;
		y = trueY;

		if ( (abs(joystick.joy1_x1) < deadZone) && (abs(joystick.joy1_y1) < deadZone) && (abs(joystick.joy1_x2) < deadZone)) //drive only if joystick out of dead zones
		{
			x = 0;
			y = 0;
			z = 0;
		}

		motorTrigger(frontRight,x*.75,-y*.75,z);
		motorTrigger(backRight,-x*.75,-y*.75,z);
		motorTrigger(frontLeft,x*.75,y*.75,z);
		motorTrigger(backLeft,-x*.75,y*.75,z);
	}
}

task getHeading() {
	HTGYROstartCal(Gyro);
	PlaySound(soundBeepBeep);
	while (true) {
		time1[T1] = 0;
		curRate = HTGYROreadRot(Gyro);
		if (abs(curRate) > 3) //sets deadzones for gyroscope
		{
			prevHeading = currHeading;
			currHeading = prevHeading + curRate * delTime; //changes current heading based on the rate of change and time elapsed
			if (currHeading > 360) currHeading -= 360; //keeps current heading between 0 and 360
			else if (currHeading < 0) currHeading += 360; // keeps curent heading between 0 and 360
		}
		wait1Msec(5);
		delTime = ((float)time1[T1]) / 1000;

	}
}

task liftFunction()
{
	int triggerValue;
	while(true)
	{
		if (abs(joystick.joy2_y2) < deadZone) //drive only if joystick out of dead zones
		{
			triggerValue = 0;
		}
		triggerValue = joystick.joy2_y2;
		motor[liftRight] = -triggerValue;
		motor[liftLeft] = triggerValue;

	}
}
task driverSweep()
{
		while(joy1Btn(5))
		{
		motor[collector] = 80;
		}

		while(joy1Btn(7))
		{
		motor[collector] = -80;
		}
}
task motorFunctions()
{
	int sweeperTrigger;
	while(true)//
	{
		if(abs(joystick.joy2_y1) < deadZone)
		{
			sweeperTrigger = 0;
		}
		sweeperTrigger =  joystick.joy2_y1;
		motor[collector] = sweeperTrigger;
	}
}
task playSong()
{
	PlaySoundFile("youngthug.rso");
	nxtDisplayBigTextLine(0,"YUNG THUG");
	wait1Msec(5000);
}
task main()
{
	initializeRobot();
	StartTask(getHeading);
	StartTask(FPSDrive);
	StartTask(playSong);
	waitForStart();
	while(true){

	}
	while(true)
	{
		getJoystickSettings(joystick);
		StartTask(motorFunctions);
		StartTask(driverSweep);
		StartTask(liftFunction);
		if (joy2Btn(3))
		{
			servo[scoreLeft] = 200;
			servo[scoreRight] = 255-200;
		}

		if (joy2Btn(4))//score position
		{
			slideBtn ++;
			if(slideBtn % 2 == 1)
			{
				servo[scoreLeft] = 255;
				servo[scoreRight] = 0;
			}
			else
			{
				servo[scoreLeft] = 35;
				servo[scoreRight] = 255-35;
			}
			wait1Msec(500);
		}
		if (joy2Btn(2) == 1)//resting position
		{
			servo[scoreLeft] = 35;
			servo[scoreRight] = 255-35;
		}

		if (joy1Btn(4)== 1)//changed 5 to 3
		{
			clampPress++;
			if(clampPress % 2 == 1)
			{
				servo[rollingSide] = 250;
				servo[rollingBack] = 250;//clamp onto rolling goal on side of robot
			}
			else
			{
				servo[rollingSide] = 200;
				servo[rollingBack] = 200;
			}
			//	servo[rollingSide] = 250;
			wait1Msec(500);
		}

		if (joy1Btn(7) == 1)
		{
			servo[rollingSide] = 200; //release rolling goal
		}

		if(joy1Btn(3) && joy1Btn(1))
		{
			PlaySound(soundFastUpwardTones);

			//initializeRobot();
			calibrate = 360 - currHeading;
		}


	}
	while (true)
		{
			wait1Msec(2000);
		}
}
